In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


Task - 1

In [5]:
import numpy as np

array_1D = np.arange(1,11)
print(array_1D)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
array_2D = np.arange(1,10).reshape(3,3)
print(array_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
list = [10,20,30,40,50]

array_list = np.array(list)

print(array_list)

[10 20 30 40 50]
int64


Task - 2

In [ ]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])

c = A+B
print(c)

d = A-B
print(d)

e = A*B
print(e)

f = A/B
print(f)

g = A**2
print(g)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]


Task - 3


In [ ]:
values = np.array([2,4,6,8,10])

square_root = np.sqrt(values)
print(square_root)

exponential = np.exp(values)
print(exponential)

natural_log = np.log(values)
print(natural_log)

sum = np.sum(values)
print(sum)

"""
    Cumulative sum means adding elements of an array step 
    by step, keeping track of the total as you go.
"""
cumulative_sum = np.cumulative_sum(values)
print(cumulative_sum)

[1.41421356 2.         2.44948974 2.82842712 3.16227766]
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
30
[ 2  6 12 20 30]


Task - 3


In [14]:
data = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]])

row_wise_sum = np.sum(data, axis=1)
print(row_wise_sum)

col_wise_sum = np.sum(data, axis=0)
print(col_wise_sum)

min_value = np.min(data)
print(min_value)

max_value = np.max(data)
print(max_value)

mean = np.mean(data)
print(mean)

[ 60 150 240]
[120 150 180]
10
90
50.0


Task - 5

In [16]:
marks = np.array([78,85,90,66,72,88,95,60])

print('mean =' ,np.mean(marks))

print('median =' ,np.median(data))

print('variance =', np.var(marks))

print('standard_deviation =', np.std(marks))

print('min =', np.min(marks))

print('max =', np.max(marks))

print('range =', np.max(marks) - np.min(marks))




mean = 79.25
median = 50.0
variance = 134.1875
standard_deviation = 11.583932838203095
min = 60
max = 95
range = 35


Task - 6

In [22]:
sorted_array = np.sort(marks)
print('sorted array =', sorted_array)

p25 = np.percentile(marks,25)
print('25th percentile =', p25)

print('p50 =', np.percentile(marks,50))

print('p75 =', np.percentile(marks,75))

avg = np.mean(marks)
print('Score above avg markd =', np.sum(print(sorted_array>avg)))

sorted array = [60 66 72 78 85 88 90 95]
25th percentile = 70.5
p50 = 81.5
p75 = 88.5
[False False False False  True  True  True  True]
Score above avg markd = None


Task - 7

In [23]:
sales = np.array([1200,1500,900,2000,1800,1700,1600])

print('total weekly sales =', np.sum(sales))

print('avg daily sales =', np.mean(sales))

print('highest and lowest sales day =', np.max(sales), np.min(sales))

print('standard deviation of sales =', np.std(sales))

avg = np.mean(sales)
print('sales above avg sales =', sales[sales>avg])

total weekly sales = 10700
avg daily sales = 1528.5714285714287
highest and lowest sales day = 2000 900
standard deviation of sales = 345.2298849598449
sales above avg sales = [2000 1800 1700 1600]
